CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "Roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "User_Roles" (
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

ALTER TABLE "User_Roles" ADD CONSTRAINT "Users_User_Roles" FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "User_Roles" ADD CONSTRAINT "Roles_User_Roles" FOREIGN KEY ("role_id") REFERENCES "Roles" ("id");
