CREATE TYPE Condition AS ENUM (
  'used',
  'like_new'
);

CREATE TABLE IF NOT EXISTS  "Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "description" varchar DEFAULT '',
  "price" decimal(6,2) NOT NULL,
  "category_id" integer NOT NULL,
  "condition" Condition NOT NULL,
  "seller_id" integer NOT NULL,
  "listed_on" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "Categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(75) NOT NULL,
  "created_on" timestamp DEFAULT (now()),
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "ProductImages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "path" varchar NOT NULL,
  "product_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "Sellers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "ProductImages" ADD CONSTRAINT "Product_Images" FOREIGN KEY ("product_id") REFERENCES "Products" ("id");

ALTER TABLE "Products" ADD CONSTRAINT "Product_Category" FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Products" ADD CONSTRAINT "Product_Seller" FOREIGN KEY ("seller_id") REFERENCES "Sellers" ("id");
